<head>
    <title>Page Not Found</title>
    <link rel="shortcut icon" href="../../assets/logo.ico" />
    <?php require "../config/bootstrap_head.php" ?>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <span class="navbar-brand"><i>SURVEY GENERATOR</i></span>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="/survey_generator/public/index.php/">FRAMEWORK</a></li>
            <li><a href="/survey_generator/public/index.php/admin">ADMINISTRATION PANEL</a></li>
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading clearfix">
            <h2 class="text-danger">404 ERROR PAGE NOT FOUND</h2>
        </div>
        <hr>
        <div class="panel-body">
            <h4 class="text-danger">No such content</h4>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php" ?>
</body>
</html>