<div id="form" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <form class="form-horizontal" method="post" action="/survey_generator/public/index.php/pages?id=<?= $id ?>">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                    <h3 class="modal-title text-primary text-center"><strong>ADD PAGE</strong></h3>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="form" value="form">
                    <div class="form-group
                        <?php
                            if ($nameError && $isSubmit) {
                                echo "has-error";
                            }
                            elseif ($isSubmit) {
                                echo "has-success";
                            } ?>
                             has-feedback" >
                        <label class="control-label col-sm-1" for="name"><strong>Name</strong></label>
                        <div class="col-sm-11">
                            <input class="form-control" id="name" placeholder="Enter name" name="name" value="<?= $name ?>">
                            <?php
                                if ($nameError && $isSubmit) {
                                    echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";
                                }
                                elseif ($isSubmit) {
                                    echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>";
                                }
                            ?>
                        </div>
                    </div>
                    <div class="form-group
                    <?php
                        if ($subjectError && $isSubmit) {
                            echo "has-error";
                        } elseif ($isSubmit) {
                            echo "has-success";
                        } ?>
                        has-feedback"">
                    <label class="control-label col-sm-1" for="subject"><strong>Subject</strong></label>
                    <div class="col-sm-11">
                        <textarea class="form-control" rows="5" id="subject" style="resize: none"
                                  placeholder="Enter subject (introduction text)" name="subject"><?= $subject ?></textarea>
                        <?php
                            if ($subjectError && $isSubmit) {
                                echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";
                            }
                            elseif ($isSubmit) {
                                echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>";
                            }
                        ?>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default pull-right">
                        <span class="text-primary">Finish</span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
<?php
    if ($nameError != '' || $subjectError != '') {
        echo  "$('#form').modal('show')";
    }
?>
</script>
