<div id="form" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <form class="form-horizontal" method="post" action="/survey_generator/public/index.php/page?id=<?= $id ?>">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                    <h3 class="modal-title text-primary text-center"><strong>ADD QUESTION</strong></h3>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="form" value="form">
                    <div class="form-group has-feedback">
                        <label class="radio-inline col-sm-offset-3">
                            <input type="radio" name="type" value="multi"
                                <?php
                                    if ($type == 'multi') {
                                        echo "checked";
                                    } else if ($type == '') {
                                        echo "checked";
                                    } ?>>
                            Multi-select
                        </label>
                        <label class="radio-inline">
                            <input type="radio" name="type" value="single"
                                <?php
                                    if ($type == 'single') {
                                        echo "checked";
                                    } ?>>
                            Single-select
                        </label>
                        <label class="radio-inline">
                            <input type="checkbox" name="mandatory" value="1"
                                <?php
                                    if ($mandatory == 1) {
                                        echo "checked";
                                    } ?> >
                            is Mandatory
                        </label>
                    </div>
                    <div class="form-group
                    <?php
                        if ($subjectError && $isSubmit) {
                            echo "has-error";
                        } elseif ($isSubmit) {
                            echo "has-success";
                        } ?>
                    has-feedback"">
                    <div class="col-sm-12">
                        <textarea class="form-control" rows="2" id="subject" style="resize: none" placeholder="Enter question subject" name="subject"><?= $subject ?></textarea>
                        <?php
                            if ($subjectError && $isSubmit) {
                                echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";
                            }
                            elseif ($isSubmit) {
                                echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>";
                            }
                        ?>
                    </div>
                    </div>
                    <div class="form-group
                        <?php
                            if ($optionsErrors[0] && $isSubmit) {
                                echo "has-error";
                            } elseif ($isSubmit) {
                                echo "has-success";
                            } ?> has-feedback" id="option1" >
                        <div class="col-sm-12">
                            <input class="form-control" placeholder="Option 1" name="option-1" value="<?= $options["option-1"] ?>">
                            <?php
                                if ($optionsErrors[0] && $isSubmit) {
                                    echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";
                                }
                                elseif ($isSubmit) {
                                    echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>";
                                }
                            ?>
                        </div>
                    </div>
                    <div class="form-group
                        <?php
                            if ($optionsErrors[1] && $isSubmit) {
                                echo "has-error";
                            } elseif ($isSubmit) {
                                echo "has-success";
                            } ?> has-feedback" id="option2">
                        <div class="col-sm-12">
                            <input class="form-control" placeholder="Option 2" name="option-2" value="<?= $options["option-2"] ?>">
                            <?php
                                if ($optionsErrors[1] && $isSubmit) {
                                    echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";
                                }
                                elseif ($isSubmit) {
                                    echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>";
                                }
                            ?>
                        </div>
                    </div>
                    <?= $optionBoxes?>
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left">
                        <span class="btn btn-default btn-sm" id="plus">
                            <strong><span class="glyphicon glyphicon-plus"></span></strong>
                        </span>
                        <span class="btn btn-default btn-sm" id="minus">
                            <strong><span class="glyphicon glyphicon-minus"></span></strong>
                        </span>
                    </div>
                    <button type="submit" class="btn btn-default pull-right"><span class="text-primary">Finish</span></button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    var plus = document.getElementById('plus');
    var minus = document.getElementById('minus');

    var options = document.querySelectorAll('*[id^="option"]');
    var last = options[options.length - 1];
    var optionCount = last.getAttribute('id').split('option')[1];
    console.log(optionCount);

    function insertAfter(newNode, referenceNode) {
        referenceNode.parentNode.insertBefore(newNode, referenceNode.nextSibling);
    }

    plus.addEventListener('click', function () {
        var lastOption = document.getElementById("option" + optionCount);
        optionCount++;
        var newOption = lastOption.cloneNode(true);
        newOption.setAttribute('id', "option" + optionCount);
        newOption.setAttribute('class', "form-group has-feedback");
        newOption.children[0].children[0].setAttribute('placeholder', "Option " + optionCount);
        newOption.children[0].children[0].value = '';
        newOption.children[0].children[0].setAttribute('name', "option-" + optionCount);
        if (newOption.children[0].children[1] != null) {
            newOption.children[0].children[1].parentNode.removeChild(newOption.children[0].children[1]);
        }
        insertAfter(newOption,lastOption);
    });

    minus.addEventListener('click', function () {
        if (optionCount > 2) {
            var lastOption = document.getElementById("option" + optionCount);
            lastOption.parentNode.removeChild(lastOption);
            optionCount--;
        }
    });

    <?php

    $optionError = false;

    foreach ($optionsErrors as $error) {
        if ($error) {
            $optionError = true;
        }
    }

    if ($subjectError || $optionError) {
        echo  "$('#form').modal('show')";
    }
    ?>
</script>
