<head>
    <?php require "../config/bootstrap_head.php" ?>
</head>
<body>
    <div class="container-fluid" align="center">
        <div class="panel panel-primary">
            <div class="panel-heading clearfix">
                <h2 class="pull-left">Administration Panel</h2>
                <div class="pull-right">
                    <button class="btn btn-success btn-md" onclick="location.href = '/survey_generator/public/index.php/survey_form';event.stopPropagation();">
                        <h4 class="center">Create a Survey</h4>
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <div class="list-group">
                        <?php \Service\SurveyGroupListDrawer::drawGroupList(1, true) ?>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <?php require "../config/bootstrap_body.php" ?>
</body>
</html>
<script>
    //Ajax pagination
    var container = document.getElementsByClassName('list-group');
    var page = 1;
    window.onscroll = function(ev) {
        if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    container[0].innerHTML += this.responseText;
                }
            };
            page++;
            xhttp.open("GET", "/survey_generator/public/index.php/admin=" + page);
            xhttp.send();

        }
    };
</script>