<head>
    <?php require "../config/bootstrap_head.php" ?>
</head>
<body>
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <form method="post" class="form-control-static" action="/survey_generator/public/index.php/survey_save?id=<?= $id ?>">
                <button type="submit" class="btn btn-primary btn-md pull-left">
                    <h4>Back</h4>
                </button>
            </form>
            <h2 class="pull-left">&nbsp;&nbsp;<?= $name ?></h2>
            <div class="pull-right">
                    <button class="btn btn-success btn-md" onclick="location.href = '/survey_generator/public/index.php/page_form?id=<?= $id ?>';event.stopPropagation();">
                        <h4 class="center">Add Page</h4>
                    </button>
            </div>
        </div>
        <div class="panel-body">
            <pre><strong> <?= $startDate ?> / <?= $expirationDate ?> </strong> <?= $subject ?>
            </pre>
            <div class="list-group">
                <?php \Service\PageGroupListDrawer::drawGroupList($id, 1, true) ?>
                </a>
            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php" ?>
</body>
</html>