<head>
    <?php require "../config/bootstrap_head.php" ?>
</head>
<body>
<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading clearfix">
            <button class="btn btn-primary btn-md pull-left" onclick="location.href = '/survey_generator/public/index.php/admin';event.stopPropagation();">
                <h4>Back</h4>
            </button>
            <h2 class="pull-left">&nbsp;&nbsp;<?= $page->getName() ?></h2>
            <h2 class="pull-right">&nbsp;&nbsp;<?= $page->getPageNumber() ." / " . $page->getPageCount() ?></h2>
        </div>
        <div class="panel-body">
            <pre><?= $page->getSubject() ?>
            </pre>
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div class="list-group">
                <?php \Service\SurveyDrawer::drawPageStats($page) ?>
            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php" ?>
</body>
</html>