<head>
    <title>Thanks for taking the survey</title>
    <link rel="shortcut icon" href="../../assets/logo.ico" />
    <?php require "../config/bootstrap_head.php" ?>

</head>
<body>
<div class="container-fluid col-lg-offset-3 col-lg-6" align="center">
    <div class="panel">
        <div class="panel-heading clearfix">
            <div class="list-group-item list-group-item-success">
            <h1 style="color:white">Thank You For Taking The Survey</h1>
            </div>
        </div>
        <hr>
        <div class="panel-body">
            <a href="/survey_generator/public/index.php/" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-home"></span> HOMEPAGE</a>
        </div>
    </div>
</div>
</body>
<?php require "../config/bootstrap_body.php" ?>

</html>