<head>
    <?php require "../config/bootstrap_head.php" ?>
</head>
<body>
<div class="container-fluid" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <h2>Framework</h2>
        </div>
        <div class="panel-body">
            <div class="list-group">
                <?php \Service\SurveyGroupListDrawer::drawFrameworkList(1, true) ?>
            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php" ?>
</body>
</html>
<script>
    //Ajax pagination
    var container = document.getElementsByClassName('list-group');
    var page = 1;
    window.onscroll = function(ev) {
        if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    container[0].innerHTML += this.responseText;
                }
            };
            page++;
            xhttp.open("GET", "/survey_generator/public/index.php/" + page);
            xhttp.send();

        }
    };
</script>