<head>
    <title>Framework</title>
    <link rel="shortcut icon" href="../../assets/logo.ico" />
    <?php require "../config/bootstrap_head.php" ?>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <span class="navbar-brand"><i>SURVEY GENERATOR</i></span>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="/survey_generator/public/index.php/">FRAMEWORK</a></li>
            <li><a href="/survey_generator/public/index.php/admin">ADMINISTRATION PANEL</a></li>
        </ul>
    </div>
</nav>
<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading clearfix">
            <h2>FRAMEWORK</h2>
        </div>
        <hr>
        <div class="panel-body">
            <div class="list-group">
                <?php \Service\SurveyGroupListDrawer::drawFrameworkList(1, true) ?>
            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php" ?>
</body>
</html>
<script>
    //Ajax pagination
    var container = document.getElementsByClassName('list-group');
    var page = 1;
    window.onscroll = function(ev) {
        if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    container[0].innerHTML += this.responseText;
                }
            };
            page++;
            xhttp.open("GET", "/survey_generator/public/index.php/" + page);
            xhttp.send();

        }
    };

    copyButtons = document.querySelectorAll('.copy');

    for (i=0 ; i < copyButtons.length ; i++) {
        copyButtons[i].addEventListener('click', copy(copyButtons[i].getAttribute('id').split('B-')[1]))
    }

    //Clipboard
    function copy(id) {
        var btn = '#B-'.concat(id);
        var copyTextareaBtn = document.querySelector(btn);

        var textarea = '#T-'.concat(id);

        copyTextareaBtn.addEventListener('click', function(event) {
            var copyTextarea = document.querySelector(textarea);
            copyTextarea.select();

            try {
                var successful = document.execCommand('copy');
                var msg = successful ? 'successful' : 'unsuccessful';
            } catch (err) {
                console.log('Oops, unable to copy');
            }
        });
    }
</script>