<head>
    <title><?= $name ?></title>
    <link rel="shortcut icon" href="../../../assets/logo.ico" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="../../../bootstrap/css/bootstrap.min.css"
    <!-- Optional theme -->
    <link rel="stylesheet" href="../../../bootstrap/css/bootstrap-theme.min.css"

</head>
<body>
<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading clearfix">
            <h2><?= $name?></h2>
            <span class="text-muted"> <?= $startDate ?> | <?= $expirationDate ?> </span>
        </div>
        <hr>
        <div class="panel-body">
            <blockquote><p><?= $subject ?></p>
            </blockquote>
            <div class="list-group">
                <a href="/survey_generator/public/index.php/survey/<?=$hash?>&1" class="btn btn-primary btn-md pull-right">Take The Survey</a>
            </div>
        </div>
    </div>
</div>
</body>

<script src="../../../bootstrap/js/jquery.min.js"></script>
<script src="../../../bootstrap/js/bootstrap.min.js"></script></body>
</html>