<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="../../../bootstrap/css/bootstrap.min.css"
    <!-- Optional theme -->
    <link rel="stylesheet" href="../../../bootstrap/css/bootstrap-theme.min.css"

</head>
<body>
<div class="container-fluid">
    <?php
        \Service\SurveyDrawer::drawSurveyPage($page, $options, $optionsError);
    ?>
</div>

<script src="../../../bootstrap/js/jquery.min.js"></script>
<script src="../../../bootstrap/js/bootstrap.min.js"></script></body>
<?php
    if (!empty($optionsError)) {
        $id = $optionsError[0];
        echo "<script>$('html,body').animate({scrollTop: $(\"#\"+{$id}).offset().top},'slow');</script>";
    }
?>
</html>