<head>
    <?php require "../config/bootstrap_head.php"?>
</head>
<body>
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <button class="btn btn-primary btn-md pull-left" onclick="location.href = '/survey_generator/public/index.php/page_save?id=<?= $id ?>';event.stopPropagation();">
                <h4>Back</h4>
            </button>
            <h2 class="pull-left">&nbsp;&nbsp;<?= $name ?></h2>
            <div class="pull-right">
                <button class="btn btn-success btn-md" onclick="location.href = '/survey_generator/public/index.php/question_form?id=<?= $id ?>';event.stopPropagation();">
                    <h4 class="center">Add Question</h4>
                </button>
            </div>
        </div>
        <div class="panel-body">
            <div class="alert alert-info">
                <h3> <?= $subject ?> </h3>
            </div>
            <div class="list-group">
                <?php \Service\QuestionGroupListDrawer::drawGroupList($id, 1, true)?>
            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php"?>
</body>
</html>