<head>
    <?php require "../config/bootstrap_head.php"?>
</head>
<body>
<div class="container-fluid" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <h2 class="pull-left"><?= $name ?></h2>
            <div class="pull-right">
                <div class="btn-group">
                    <button class="btn btn-info btn-md" onclick="location.href = '#';event.stopPropagation();">
                        <h4 class="center">Save</h4>
                    </button>
                    <button class="btn btn-success btn-md" onclick="location.href = '/survey_generator/public/index.php/question_form?id=<?= $id ?>';event.stopPropagation();">
                        <h4 class="center">Add Question</h4>
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="alert alert-info">
                <h3> <?= $subject ?> </h3>
            </div>
            <div class="list-group">

            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php"?>
</body>
</html>