<head>
    <?php require "../config/bootstrap_head.php"?>
</head>
<body>
<div class="container-fluid" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <div class="pull-left">
                <button class="btn btn-primary btn-md" onclick="location.href = '/survey_generator/public/index.php/pages?id=<?= $id ?>';event.stopPropagation();">
                    <h4>Back</h4>
                </button>
            </div>
            <h2 class="text-center">Page Form</h2>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                <input type="hidden" name="form" value="form">
                <div class="form-group <?php if ($nameError && $isSubmit) { echo "has-error"; } elseif ($isSubmit) { echo "has-success"; } ?> has-feedback" >
                    <label class="control-label col-sm-3" for="name">Name:</label>
                    <div class="col-sm-6">
                        <input class="form-control" id="name" placeholder="Enter name" name="name" value="<?= $name ?>">
                        <?php
                            if ($nameError && $isSubmit) { echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";}
                            elseif ($isSubmit) { echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>"; }
                        ?>
                    </div>
                </div>
                <div class="form-group <?php if ($subjectError && $isSubmit) { echo "has-error"; } elseif ($isSubmit) { echo "has-success"; } ?> has-feedback"">
                <label class="control-label col-sm-3" for="subject">Subject:</label>
                <div class="col-sm-6">
                    <textarea class="form-control" rows="5" id="subject" style="resize: none" placeholder="Enter subject (introduction text)" name="subject"><?= $subject ?></textarea>
                    <?php
                        if ($subjectError && $isSubmit) { echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";}
                        elseif ($isSubmit) { echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>"; }
                    ?>
                </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <button type="submit" class="btn btn-success">Finish</button>
            </div>
        </div>
            </form>
        </div>
</div>

    <?php require "../config/bootstrap_body.php"?>
</body>
</html>