<head>
    <?php require "../config/bootstrap_head.php"?>

</head>
<body>
<div class="container-fluid" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <div class="pull-left">
                <button class="btn btn-default btn-md" onclick="location.href = '/survey_generator/public/index.php/admin';event.stopPropagation();">
                    <h4>Back</h4>
                </button>
            </div>
            <h2 class="text-center">Survey Form</h2>
        </div>
        <div class="panel-body">
                <form class="form-horizontal" method="post">
                    <input type="hidden" name="form" value="form">
                    <div class="form-group <?php if ($nameError && $isSubmit) { echo "has-error"; } elseif ($isSubmit) { echo "has-success"; } ?> has-feedback" >
                        <label class="control-label col-sm-3" for="name">Name:</label>
                        <div class="col-sm-6">
                            <input class="form-control" id="name" placeholder="Enter name" name="name" value="<?= $name ?>">
                           <?php
                               if ($nameError && $isSubmit) { echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";}
                               elseif ($isSubmit) { echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>"; }
                               ?>
                        </div>
                    </div>
                    <div class="form-group <?php if ($subjectError && $isSubmit) { echo "has-error"; } elseif ($isSubmit) { echo "has-success"; } ?> has-feedback"">
                        <label class="control-label col-sm-3" for="subject">Subject:</label>
                        <div class="col-sm-6">
                            <textarea class="form-control" rows="5" id="subject" style="resize: none" placeholder="Enter subject (introduction text)" name="subject"><?= $subject ?></textarea>
                            <?php
                                if ($subjectError && $isSubmit) { echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";}
                                elseif ($isSubmit) { echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>"; }
                            ?>
                        </div>
                    </div>
                    <div class="form-group <?php if ($startDateError && $isSubmit) { echo "has-error"; } elseif ($isSubmit) { echo "has-success"; } ?> has-feedback"">
                        <label class="control-label col-sm-5 " for="start_date">
                            Start Date:
                        </label>
                        <div class="col-sm-2">
                            <div class="input-group">
                                <input class="form-control" id="start_date" name="start_date" placeholder="YYYY-MM-DD" type="text" value="<?= $startDate ?>"/>
                            </div>
                            <?php
                                if ($startDateError && $isSubmit) { echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";}
                                elseif ($isSubmit) { echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>"; }
                            ?>
                        </div>
                    </div>
                    <div class="form-group <?php if ($expirationDateError && $isSubmit) { echo "has-error"; } elseif ($isSubmit) { echo "has-success"; } ?> has-feedback"">
                        <label class="control-label col-sm-5 " for="expiration_date">
                            Expiration Date:
                        </label>
                        <div class="col-sm-2">
                            <div class="input-group">
                                <input class="form-control" id="expiration_date" name="expiration_date" placeholder="YYYY-MM-DD" type="text"/ value="<?= $expirationDate ?>">
                            </div>
                            <?php
                                if ($expirationDateError && $isSubmit) { echo "<span class='glyphicon glyphicon-remove form-control-feedback'></span>";}
                                elseif ($isSubmit) { echo "<span class='glyphicon glyphicon-ok form-control-feedback'></span>"; }
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-8">
                            <button type="submit" class="btn btn-success">Finish</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php require "../config/bootstrap_body.php"?>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

</body>
<script>
    $(document).ready(function(){
        var date_input=$('input[name="start_date"]'); //our date input has the name "date"
        var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
        date_input.datepicker({
            format: 'yyyy-mm-dd',
            container: container,
            todayHighlight: true,
            autoclose: true,
        })
    })
    $(document).ready(function(){
        var date_input=$('input[name="expiration_date"]'); //our date input has the name "date"
        var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
        date_input.datepicker({
            format: 'yyyy-mm-dd',
            container: container,
            todayHighlight: true,
            autoclose: true,
        })
    })
</script>
</html>
